apiVersion: v1
kind: Pod
metadata:
  name: staticresponse-pod
spec:
  containers:
    # This is where the application container would go, for example
    # - name: some-name
    #   image: some-image
    - name: staticresponse
      image: nginx
      volumeMounts:
      - name: staticresponse-config
        mountPath: /etc/nginx/conf.d
  volumes:
    - name: staticresponse-config
      configMap:
        name: staticresponse-config