apiVersion: v1
kind: Pod
metadata:
  name: staticfiles-pod
spec:
  containers:
    # This is where the application container would go, for example
    # - name: some-name
    #   image: some-image
    - name: staticfiles
      image: nginx
      volumeMounts:
      - name: staticfiles-config
        mountPath: /etc/nginx/conf.d
      - name: staticfiles-www
        mountPath: /data/www
  volumes:
    - name: staticfiles-config
      configMap:
        name: staticfiles-config
    - name: staticfiles-www
      configMap:
        name: staticfiles-www