apiVersion: v1
kind: Pod
metadata:
  name: staticfilesmulti-pod
spec:
  containers:
    # This is where the application container would go, for example
    # - name: some-name
    #   image: some-image
    - name: staticfilesmulti
      image: nginx
      volumeMounts:
      - name: staticfilesmulti-config
        mountPath: /etc/nginx/conf.d
      - name: staticfilesmulti-www
        mountPath: /data/www
      - name: staticfilesmulti-images
        mountPath: /data/images
  volumes:
    - name: staticfilesmulti-config
      configMap:
        name: staticfilesmulti-config
    - name: staticfilesmulti-www
      configMap:
        name: staticfilesmulti-www
    - name: staticfilesmulti-images
      configMap:
        name: staticfilesmulti-images